from random import randint
from emoji import emojize

print (" \n Based on the following  game we designed in the class: \n")
print ("create menu-driven programming that the user can select what kind of game they want to play\n".upper())

def singlePlayer(): # Single player Gessing Game

    print (" In this game you need to guess the number between 1 and 100 Generated by the computer")
    randNum = randint(1,100) 
    # randNum = randint(1,1) 
    counter = 0

    while True:
        guess = int(input("Type a number: "))
        # guess = 1
        counter += 1

        if guess < randNum :
            print('Sorry try again, \n Something bigger this time')

        elif guess > randNum:
            print('Sorry try again, \n Something smaller this time')

        else:
            print(" \033[1;32;40m CONGRATULATIONS!!! \033[m".ljust(40,emojize(":confetti_ball:")))
            print(f" \033[1;32;40m YOU WIN WITH {counter} TRIES \033[m")
            break 

singlePlayer()

def gameMenu ():
    print("".center(50, emojize(":video_game:")))
    print(" MAIN MENU ".center(100, " "))
    print("".center(50, emojize(":video_game:")))
    print('\n 1 - SINGLE PLAYER',emojize(":video_game:"))
    print('\n 2 - MULTIPLAYER',emojize(":video_game:")," VS ", emojize(":video_game:"))
    print('\n 3 - play the game two player (alternative): ')
    print('\n 4 - exit',emojize(":door:"))
    return input('\n Select the menu : (1,2,3, 4) : ')

